### ISSUE TITLE
Fix various TODO

### ISSUE THREAD

**Issue by seletskiy** [seletskiy/go-android-rpc#15]
- [ ] [move operations on that map to method, so generated code will not](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/android/android.go#L15)
- [ ] [not implemented](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/android/android.go#L24)
- [ ] [consider own bindings](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/android/android.go#L78)
- [ ] [create interface for Views](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/android/android.go#L91)
- [ ] [validation via init functions in every generated code file](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/android/android.go#L105)
- [ ] [become recursive to allow nested ViewGroups](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerListViews.java#L13)
- [ ] [proper exception handling](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerListViews.java#L38)
- [ ] [move package name to go code generator](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerCallViewMethod.java#L30)
- [ ] [src/com/example/groid/RpcHandlerCallViewMethod.java](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerCallViewMethod.java#L44)
- [ ] [src/com/example/groid/RpcHandlerCallViewMethod.java](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerCallViewMethod.java#L57)
- [ ] [src/com/example/groid/RpcHandlerCallViewMethod.java](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerCallViewMethod.java#L115)
- [ ] [src/com/example/groid/RpcHandlerCallViewMethod.java](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerCallViewMethod.java#L127)
- [ ] [src/com/example/groid/RpcHandlerSubscribeToViewEvent.java](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerSubscribeToViewEvent.java#L36)
- [ ] [src/com/example/groid/RpcHandlerSubscribeToViewEvent.java](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerSubscribeToViewEvent.java#L62)
- [ ] [src/com/example/groid/RpcHandlerSubscribeToViewEvent.java](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerSubscribeToViewEvent.java#L104)
- [ ] [handle errors](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/MainActivity.java#L51)
- [ ] [proper exception handling](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/MainActivity.java#L64)
- [ ] [properly return json error](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/MainActivity.java#L68)
- [ ] [src/com/example/groid/RpcHandlerSubscribeToSensorValues.java](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/src/com/example/groid/RpcHandlerSubscribeToSensorValues.java#L70)
- [ ] [fix me when #7 is ready](https://github.com/seletskiy/go-android-rpc/blob/b554bb3a1cedbf0ff3af9c3a0adae1dab24982f6/api-code-generation/main.go#L160)
